version: 0.2

phases:
  install:
    commands:
      # Install Amazon Corretto 11 (Java 11)
      echo Installing Amazon Corretto 11...
      sudo yum install -y java-11-amazon-corretto-devel || { echo 'Java installation failed'; exit 1; }

      # Set JAVA_HOME and update PATH
      echo Setting JAVA_HOME and PATH...
      export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
      export PATH=$JAVA_HOME/bin:$PATH
      echo "JAVA_HOME: $JAVA_HOME"
      echo "PATH: $PATH"

      # Verify Java installation
      java -version
      echo JAVA_HOME is set to $JAVA_HOME
      echo PATH is set to $PATH

      # Install Maven 3.9.9
      echo Installing Maven...
      curl -sL https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.tar.gz | tar xz -C /tmp || { echo 'Maven installation failed'; exit 1; }
      export M2_HOME=/tmp/apache-maven-3.9.9
      export PATH=$M2_HOME/bin:$PATH

      # Verify Maven installation
      mvn --version || { echo 'Maven verification failed'; exit 1; }

  build:
    commands:
      # Compile and package the project
      echo Compiling the project...
      mvn compile
      echo Packaging the project...
      mvn package -DskipTests=true

  post_build:
    commands:
      # Run the application
      echo Running the application...
      cd target/
      java -jar Assignment3_MihyeBang-0.0.1-SNAPSHOT.jar

artifacts:
  files:
    - target/Assignment3_MihyeBang-0.0.1-SNAPSHOT.jar
  discard-paths: yes
